// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (sql.Result, error)
	CreateTeam(ctx context.Context, name string) (sql.Result, error)
	CreateTurn(ctx context.Context, arg CreateTurnParams) (sql.Result, error)
	DeletePerson(ctx context.Context, arg DeletePersonParams) error
	DeleteTeam(ctx context.Context, id int64) error
	DeleteTurn(ctx context.Context, arg DeleteTurnParams) error
	GetPerson(ctx context.Context, arg GetPersonParams) (GetPersonRow, error)
	GetTeam(ctx context.Context, id int64) (GetTeamRow, error)
	GetTurn(ctx context.Context, arg GetTurnParams) (GetTurnRow, error)
	GetTurnByDate(ctx context.Context, arg GetTurnByDateParams) (GetTurnByDateRow, error)
	GetTurnByDateAndTeam(ctx context.Context, arg GetTurnByDateAndTeamParams) (GetTurnByDateAndTeamRow, error)
	ListPeople(ctx context.Context, teamID int64) ([]ListPeopleRow, error)
	ListTeams(ctx context.Context) ([]ListTeamsRow, error)
	ListTurns(ctx context.Context, arg ListTurnsParams) ([]ListTurnsRow, error)
	ListTurnsWithBothDates(ctx context.Context, arg ListTurnsWithBothDatesParams) ([]ListTurnsWithBothDatesRow, error)
	ListTurnsWithDateFrom(ctx context.Context, arg ListTurnsWithDateFromParams) ([]ListTurnsWithDateFromRow, error)
	ListTurnsWithDateTo(ctx context.Context, arg ListTurnsWithDateToParams) ([]ListTurnsWithDateToRow, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (sql.Result, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (sql.Result, error)
	UpdateTurn(ctx context.Context, arg UpdateTurnParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
